### ISSUE TITLE
Typo on line 59

### ISSUE THREAD

**Issue by pepeuDotCom** [sebasvelasco353/CreativeCoding_MakingVisualsWithJavaScript__domestikaCourse#1]
Heya, I needed a copy of the 03.js to show a friend where I was in the course, (mine was at home), and found yours. I noticed a little typo that causes the distance calculation be a bit off. 
return Math.sqrt(dx * dx + dy + dy);
should be 
return Math.sqrt(dx * dx + dy * dy);

Cheers!

**Comment by sebasvelasco353** [comment]
Hahaha Thank you very much pepeuDotCom, just changed it to what you said.
thnx!
